version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: "America/New_York"
      WEBPASSWORD: "yourpassword"
      DNS1: 127.0.0.1#5335
      DNS2: 127.0.0.1#5335
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart: unless-stopped

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    restart: unless-stopped
